package views;

import components.ImageLabel;
import utils.AppColors;

public class MulticastChat extends javax.swing.JFrame {
  private static MulticastChat instance;
  private final String PATH_IMG_LABEL = "/logo.png";
  
  private MulticastChat() {
    initComponents();
    setLocationRelativeTo(null);
  }
  
  public static MulticastChat getInstance() {
    if(instance == null) {
      instance = new MulticastChat();
    }
    
    return instance;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelChat = new javax.swing.JPanel();
        PanelLateral = new javax.swing.JPanel();
        LabelUsers = new javax.swing.JLabel();
        LabelGroups = new javax.swing.JLabel();
        panelGroups1 = new javax.swing.JPanel();
        BtnFriend = new javax.swing.JButton();
        labelImg = new ImageLabel(PATH_IMG_LABEL);
        panelGroups = new javax.swing.JPanel();
        BtnGroup1 = new javax.swing.JButton();
        userInfoComponent = new components.UserInfoComponent();
        ContainerMessage = new javax.swing.JPanel();
        textFieldMessage = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelChat.setBackground(new java.awt.Color(236, 236, 236));
        PanelChat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLateral.setBackground(AppColors.getPRIMARY_COLOR());
        PanelLateral.setBackground(new java.awt.Color(153, 0, 0));
        PanelLateral.setForeground(new java.awt.Color(255, 255, 255));
        PanelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelUsers.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        LabelUsers.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelUsers.setText("En línea");
        PanelLateral.add(LabelUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 70, -1));

        LabelGroups.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        LabelGroups.setForeground(new java.awt.Color(255, 255, 255));
        LabelGroups.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelGroups.setText("Grupos");
        PanelLateral.add(LabelGroups, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, -1));

        panelGroups1.setBackground(new java.awt.Color(229, 229, 229));
        panelGroups1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnFriend.setBackground(new java.awt.Color(153, 0, 0));
        BtnFriend.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        BtnFriend.setForeground(new java.awt.Color(255, 255, 255));
        BtnFriend.setText("Toalá");
        BtnFriend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFriendActionPerformed(evt);
            }
        });
        panelGroups1.add(BtnFriend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, -1));

        PanelLateral.add(panelGroups1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 180, 180));

        labelImg.setPreferredSize(new java.awt.Dimension(250, 250));
        PanelLateral.add(labelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 60));

        panelGroups.setBackground(new java.awt.Color(229, 229, 229));
        panelGroups.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnGroup1.setBackground(new java.awt.Color(153, 0, 0));
        BtnGroup1.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        BtnGroup1.setForeground(new java.awt.Color(255, 255, 255));
        BtnGroup1.setText("Animatrónicos");
        BtnGroup1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelGroups.add(BtnGroup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, -1));

        PanelLateral.add(panelGroups, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, 90));

        userInfoComponent.setBackground(new java.awt.Color(204, 204, 204));
        PanelLateral.add(userInfoComponent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 200, -1));

        PanelChat.add(PanelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 700));

        ContainerMessage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldMessage.setBackground(new java.awt.Color(190, 190, 190));
        textFieldMessage.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        textFieldMessage.setForeground(new java.awt.Color(255, 255, 255));
        textFieldMessage.setText("Enviar mensaje");
        textFieldMessage.setBorder(null);
        textFieldMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMessageActionPerformed(evt);
            }
        });
        ContainerMessage.add(textFieldMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 630, 40));

        PanelChat.add(ContainerMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, 770, 60));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Esta Navidad, lo que importa es estar conectados... ¡Feliz Navichat!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelChat.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 780, 50));
        PanelChat.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 760, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void textFieldMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMessageActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_textFieldMessageActionPerformed

    private void BtnFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFriendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnFriendActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MulticastChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MulticastChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MulticastChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MulticastChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MulticastChat().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFriend;
    private javax.swing.JButton BtnGroup1;
    private javax.swing.JPanel ContainerMessage;
    private javax.swing.JLabel LabelGroups;
    private javax.swing.JLabel LabelUsers;
    private javax.swing.JPanel PanelChat;
    private javax.swing.JPanel PanelLateral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelImg;
    private javax.swing.JPanel panelGroups;
    private javax.swing.JPanel panelGroups1;
    private javax.swing.JTextField textFieldMessage;
    private components.UserInfoComponent userInfoComponent;
    // End of variables declaration//GEN-END:variables
}
