package components;

import java.awt.Cursor;
import javax.swing.JButton;

public class BtnFriend extends javax.swing.JPanel {
  private int contador;
  
  public BtnFriend() {
    initComponents();
    btnUsername.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    contador = 0;
  }
  
  public void setUsername(String username) {
    btnUsername.setText(username);
  }
  
  public JButton getBtnUsername() {
    return this.btnUsername;
  }
  
  public void incrementCounter() {
    this.contador++;
    messageCounter.setText(String.valueOf(this.contador));
  }
  
  public void resetCounter() {
    this.contador = 0;
    messageCounter.setText("");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnUsername = new javax.swing.JButton();
    messageCounter = new javax.swing.JLabel();

    setBackground(new java.awt.Color(255, 255, 255));
    setMaximumSize(new java.awt.Dimension(180, 30));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btnUsername.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
    btnUsername.setText("Usuario");
    add(btnUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

    messageCounter.setBackground(new java.awt.Color(37, 37, 37));
    messageCounter.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
    messageCounter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    messageCounter.setText("0");
    add(messageCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 30, 30));
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnUsername;
  private javax.swing.JLabel messageCounter;
  // End of variables declaration//GEN-END:variables
}
