package components;

import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;
import utils.FontAwesomeIcons;

public class FileComponent extends javax.swing.JPanel {
  private String path;
  /**
   * Creates new form FileComponent
   * @param filename
   * @param filesize
   * @param username
   * @param path
   */
  public FileComponent(String filename, String filesize, String username, String path) {
    initComponents();
    this.path = path;
    labelUsername.setText(username);
    labelFilename.setText(filename);
    labelFileSize.setText(filesize);
  }
  
  public void setPathFile(String path) {
    this.path = path;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelFilename = new javax.swing.JLabel();
    labelFileSize = new javax.swing.JLabel();
    labelFileIcon = new javax.swing.JLabel();
    btnOpenFile = new javax.swing.JButton();
    labelUsername = new javax.swing.JLabel();

    setBackground(new java.awt.Color(204, 204, 204));
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setMaximumSize(new java.awt.Dimension(290, 90));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    labelFilename.setBackground(new java.awt.Color(204, 204, 204));
    labelFilename.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
    labelFilename.setForeground(new java.awt.Color(0, 0, 0));
    labelFilename.setText("Nombre del Archivo");
    add(labelFilename, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

    labelFileSize.setBackground(new java.awt.Color(204, 204, 204));
    labelFileSize.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
    labelFileSize.setForeground(new java.awt.Color(0, 0, 0));
    labelFileSize.setText("Peso del archivo");
    add(labelFileSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

    labelFileIcon.setIcon(FontAwesomeIcons.fileIcon(50));
    labelFileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labelFileIcon.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
    add(labelFileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 24, 100, 70));

    btnOpenFile.setBackground(new java.awt.Color(204, 0, 0));
    btnOpenFile.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
    btnOpenFile.setForeground(new java.awt.Color(255, 255, 255));
    btnOpenFile.setText("Abrir archivo");
    btnOpenFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnOpenFileActionPerformed(evt);
      }
    });
    add(btnOpenFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 140, -1));

    labelUsername.setBackground(new java.awt.Color(204, 0, 0));
    labelUsername.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
    labelUsername.setForeground(new java.awt.Color(0, 0, 0));
    labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    labelUsername.setText("Usuario");
    add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, -1));
  }// </editor-fold>//GEN-END:initComponents

  private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
    if(path != null && !path.isEmpty()) {
      File file = new File(path);
      if(!file.exists()) {
        JOptionPane.showMessageDialog(this, "El archivo no existe" + file.getAbsolutePath(), "Error", JOptionPane.ERROR_MESSAGE);
        return;
      }  
      
      try {
        Desktop desktop = Desktop.getDesktop();
        desktop.open(file);
      } catch (Exception e) {
      }
    }
  }//GEN-LAST:event_btnOpenFileActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnOpenFile;
  private javax.swing.JLabel labelFileIcon;
  private javax.swing.JLabel labelFileSize;
  private javax.swing.JLabel labelFilename;
  private javax.swing.JLabel labelUsername;
  // End of variables declaration//GEN-END:variables
}
