package components;

import utils.AppColors;
public class MessageComponent extends javax.swing.JPanel {
  public MessageComponent() {
    initComponents();
  }
  
  public void setMessage(String message) {
    labelMessage.setText(message);
  }
  
  public void setUsername(String username) {
    labelUsername.setText(username); 
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelUsername = new javax.swing.JLabel();
    labelMessage = new javax.swing.JLabel();

    setMaximumSize(new java.awt.Dimension(500, 40));

    labelUsername.setBackground(new java.awt.Color(255, 255, 255));
    labelUsername.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
    labelUsername.setForeground(new java.awt.Color(0, 0, 0));
    labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    labelUsername.setText("Usuario");

    labelMessage.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
    labelMessage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    labelMessage.setText("Mensaje");
    labelMessage.setBackground(AppColors.getPRIMARY_COLOR());

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(393, Short.MAX_VALUE)
        .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
      .addComponent(labelMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(labelUsername)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(labelMessage))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel labelMessage;
  private javax.swing.JLabel labelUsername;
  // End of variables declaration//GEN-END:variables
}
