/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import javax.swing.SwingConstants;
import utils.FontAwesomeIcons;

/**
 *
 * @author serge
 */
public class UserInfoComponent extends javax.swing.JPanel {

  /**
   * Creates new form UserInfoComponent
   */
  public UserInfoComponent() {
    initComponents();
    setIconUser();
  }
  
  private void setIconUser () {
    this.labelUserIcon.setIcon(FontAwesomeIcons.userIcon(40));
    this.labelUserIcon.setHorizontalAlignment(SwingConstants.CENTER);
    this.labelUserIcon.setVerticalAlignment(SwingConstants.CENTER);
  }
  
  public void setUsernameLabel(String username) {
    this.labelUsername.setText(username);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelUsername = new javax.swing.JLabel();
    labelUserIcon = new javax.swing.JLabel();

    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    labelUsername.setBackground(new java.awt.Color(204, 0, 51));
    labelUsername.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
    labelUsername.setForeground(new java.awt.Color(255, 255, 255));
    labelUsername.setText("Username");
    add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 110, -1));
    add(labelUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 100));
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel labelUserIcon;
  private javax.swing.JLabel labelUsername;
  // End of variables declaration//GEN-END:variables
}
